# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeApp' do

   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
   pod 'SwiftyJSON', '~> 4.0'
   pod 'Alamofire', '~> 4.7'

end
